In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

import warnings
warnings.filterwarnings("ignore")

# fix_yahoo_finance is used to fetch data 
import fix_yahoo_finance as yf

In [34]:
symbols = ['AMZN', 'MSFT', 'GOOGL',]
start = '2016-01-01'
end = '2019-01-01'

In [35]:
df = yf.download(symbols,start,end)['Adj Close']

[*********************100%***********************]  14 of 14 completed

In [36]:
df

,AAPL,ADBE,AMZN,CLDR,CRM,DVMT,EQIX,FB,FEYE,FIVN,GOOGL,INTC,NFLX,PAYC
Date,,,,,,,,,,,,,,
2015-12-31,97.864746,93.940002,675.890015,NaN,78.400002,NaN,276.282532,104.660004,20.740000,8.700000,778.010010,30.541851,114.379997,37.630001
2016-01-04,97.948441,91.970001,636.989990,NaN,76.709999,NaN,270.508423,102.220001,21.870001,8.250000,759.440002,30.134039,109.959999,35.970001
2016-01-05,95.493919,92.339996,633.789978,NaN,77.050003,NaN,277.205322,102.730003,21.639999,8.520000,761.530029,29.992189,107.660004,34.869999
2016-01-06,93.625145,91.019997,632.650024,NaN,76.290001,NaN,282.431305,102.970001,20.530001,8.410000,759.330017,29.327276,117.680000,34.990002
2016-01-07,89.673714,89.110001,607.940002,NaN,74.300003,NaN,277.095703,97.919998,19.010000,8.040000,741.000000,28.227942,114.559998,35.540001
2016-01-08,90.147873,87.849998,607.049988,NaN,73.230003,NaN,283.034363,97.330002,18.320000,8.020000,730.909973,27.935379,111.389999,33.259998
2016-01-11,91.607574,89.379997,617.739990,NaN,73.180000,NaN,285.857483,97.510002,17.379999,8.010000,733.070007,28.422985,114.970001,32.959999
2016-01-12,92.937134,89.820000,617.890015,NaN,74.459999,NaN,287.721252,99.370003,16.850000,8.340000,745.340027,28.972647,116.580002,33.230000
2016-01-13,90.547684,88.300003,581.809998,NaN,72.349998,NaN,279.187897,95.440002,16.639999,7.800000,719.570007,28.290001,106.559998,30.900000
2016-01-14,92.528015,89.800003,593.000000,NaN,73.070000,NaN,284.130646,98.370003,16.700001,7.520000,731.390015,29.025843,107.059998,31.809999
2016-01-15,90.305962,89.169998,570.179993,NaN,70.860001,NaN,277.004333,94.970001,16.340000,7.380000,710.489990,26.383909,104.040001,32.020000
2016-01-19,89.868973,89.180000,574.479980,NaN,70.800003,NaN,269.622192,95.260002,15.230000,7.120000,719.080017,26.419363,107.889999,31.040001
2016-01-20,89.989838,87.940002,571.770020,NaN,70.330002,NaN,268.936981,94.349998,14.870000,7.200000,718.559998,26.233196,107.739998,30.820000
2016-01-21,89.534256,88.000000,575.020020,NaN,69.510002,NaN,264.752533,94.160004,14.790000,7.250000,726.669983,26.295254,102.349998,31.420000
2016-01-22,94.294540,89.629997,596.380005,NaN,71.550003,NaN,271.394684,97.940002,16.030001,7.560000,745.460022,26.534620,100.720001,32.299999
2016-01-25,92.453667,86.769997,596.530029,NaN,69.919998,NaN,274.025879,97.010002,14.790000,7.370000,733.619995,26.242056,99.120003,31.240000
2016-01-26,92.965019,86.889999,601.250000,NaN,69.870003,NaN,277.415466,97.339996,14.740000,7.560000,733.789978,26.543489,97.830002,30.500000
2016-01-27,86.856606,84.849998,583.349976,NaN,67.430000,NaN,273.697052,94.449997,14.170000,7.650000,717.580017,26.428236,91.150002,28.780001
2016-01-28,87.479507,84.519997,635.349976,NaN,65.690002,NaN,274.290833,109.110001,13.770000,8.040000,748.299988,26.570084,94.410004,29.219999
2016-01-29,90.501190,89.129997,587.000000,NaN,68.059998,NaN,283.746948,112.209999,14.090000,8.330000,761.349976,27.500967,91.839996,30.150000
2016-02-01,89.655136,89.610001,574.809998,NaN,68.440002,NaN,284.541870,115.089996,14.410000,8.410000,770.770020,27.323658,94.089996,31.340000
2016-02-02,87.842140,87.949997,552.099976,NaN,64.519997,NaN,285.592499,114.610001,13.930000,8.290000,780.909973,26.419363,91.489998,30.900000
2016-02-03,89.580750,87.989998,531.070007,NaN,65.339996,NaN,282.805939,112.690002,14.180000,8.240000,749.380005,26.240496,90.739998,30.270000
2016-02-04,90.300537,86.360001,536.260010,NaN,67.199997,NaN,281.810059,110.489998,14.710000,8.710000,730.030029,26.625072,89.709999,30.969999
2016-02-05,87.888779,79.199997,502.130005,NaN,58.509998,NaN,263.528290,104.070000,13.210000,7.060000,703.760010,25.972191,82.790001,26.510000
2016-02-08,88.814240,74.940002,488.100006,NaN,54.049999,NaN,245.621033,99.750000,11.960000,6.660000,704.159973,25.775429,83.320000,24.240000
2016-02-09,88.795532,73.849998,482.070007,NaN,57.330002,NaN,242.158401,99.540001,12.020000,6.900000,701.020020,25.766485,86.129997,22.500000
2016-02-10,88.122475,75.529999,490.480011,NaN,58.759998,NaN,249.732391,101.000000,12.470000,6.410000,706.849976,25.247757,88.449997,23.580000
2016-02-11,87.589630,74.940002,503.820007,NaN,59.240002,NaN,251.294708,101.910004,12.410000,6.300000,706.359985,25.238810,86.349998,24.360001
2016-02-12,87.860733,76.669998,507.079987,NaN,59.680000,NaN,260.275696,102.010002,12.000000,6.200000,706.890015,25.614449,87.400002,24.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-15,187.622253,239.949997,1619.439941,12.15,132.490005,105.059998,374.679962,143.850006,18.799999,42.770000,1071.050049,46.446583,290.059998,124.699997
2018-11-16,189.700302,238.889999,1593.410034,12.15,132.550003,104.470001,377.937805,139.529999,18.760000,42.970001,1068.270020,47.141689,286.209991,123.620003
2018-11-19,182.182083,219.690002,1512.290039,11.23,121.010002,103.300003,372.919739,131.550003,17.670000,38.419998,1027.420044,46.340385,270.600006,113.180000
2018-11-20,173.477814,219.729996,1495.459961,10.69,120.669998,102.639999,366.141571,132.429993,17.610001,36.259998,1030.449951,45.751472,266.980011,114.000000
2018-11-21,173.281754,225.979996,1516.729980,11.40,123.589996,102.989998,372.355713,134.820007,17.910000,37.340000,1043.430054,45.403919,262.130005,120.040001
2018-11-23,168.880600,225.559998,1502.060059,11.33,122.029999,103.919998,369.934204,131.729996,18.500000,37.910000,1030.099976,44.930866,258.820007,119.150002
2018-11-26,171.164505,231.960007,1581.329956,11.88,126.410004,105.629997,371.655518,136.380005,19.070000,39.669998,1055.939941,45.809402,261.429993,122.830002
2018-11-27,170.792038,232.250000,1581.420044,11.66,127.540001,104.660004,371.597168,135.000000,19.080000,40.049999,1052.280029,46.407963,266.630005,121.489998
2018-11-28,177.359451,249.210007,1677.750000,12.44,140.639999,106.599998,373.493500,136.759995,19.700001,41.279999,1091.790039,47.170650,282.649994,130.050003
2018-11-29,175.996933,249.089996,1673.569946,12.35,139.720001,106.000000,373.542145,138.679993,19.850000,40.860001,1094.579956,46.050762,288.750000,131.369995
2018-11-30,175.046158,250.889999,1690.170044,12.34,142.759995,105.480003,374.679962,140.610001,20.010000,42.880001,1109.650024,47.605095,286.130005,132.770004
2018-12-03,181.162659,255.259995,1772.359985,12.31,144.149994,105.529999,380.349579,141.089996,20.010000,42.700001,1116.359985,48.396740,290.299988,134.729996
2018-12-04,173.193542,245.820007,1668.400024,11.59,139.240005,104.459999,374.495209,137.929993,19.600000,40.380001,1062.469971,46.099030,275.329987,131.000000
2018-12-06,171.262527,250.630005,1699.189941,13.01,142.059998,105.610001,381.915283,139.630005,20.209999,41.320000,1078.079956,46.697594,282.880005,133.570007
2018-12-07,165.155823,238.000000,1629.130005,12.25,135.949997,104.000000,375.837189,137.419998,19.430000,40.220001,1046.579956,44.641239,265.140015,129.639999
2018-12-10,166.243851,244.089996,1641.030029,12.73,137.270004,104.110001,376.430420,141.850006,19.750000,41.060001,1053.180054,45.577694,269.700012,131.720001
2018-12-11,165.293045,245.339996,1643.239990,12.32,136.789993,104.730003,379.075592,142.080002,18.860001,41.750000,1061.650024,45.741825,265.320007,131.619995
2018-12-12,165.753738,245.550003,1663.540039,12.64,140.089996,105.010002,376.469360,144.500000,19.520000,44.040001,1073.729980,46.176270,274.880005,134.589996
2018-12-13,167.567123,248.080002,1658.380005,12.39,141.139999,105.500000,378.608795,145.009995,18.620001,43.980000,1073.540039,46.620358,276.019989,133.360001
2018-12-14,162.205368,230.000000,1591.910034,12.34,137.039993,105.790001,376.255371,144.059998,18.580000,42.049999,1051.709961,46.205227,266.839996,130.619995
2018-12-17,160.695862,221.380005,1520.910034,11.36,130.830002,105.080002,358.906189,140.190002,17.570000,40.740002,1025.650024,45.452202,262.799988,123.349998
2018-12-18,162.783722,226.179993,1551.479980,11.66,132.320007,105.860001,360.763672,143.660004,17.809999,42.340000,1043.410034,46.089378,270.940002,124.870003
2018-12-19,157.706192,224.649994,1495.079956,11.18,131.160004,104.849998,358.303284,133.240005,17.510000,42.880001,1035.459961,43.994404,266.769989,123.650002
2018-12-20,153.726532,218.649994,1460.829956,11.10,127.730003,103.410004,348.354736,133.399994,16.910000,40.650002,1023.580017,43.965443,260.579987,119.559998
2018-12-21,147.747253,208.800003,1377.449951,10.36,122.910004,102.730003,340.672089,124.949997,15.970000,39.320000,991.250000,43.289646,246.389999,115.010002
2018-12-24,143.924454,205.160004,1343.959961,10.37,121.330002,80.500000,329.692627,124.059998,15.390000,39.259998,984.669983,42.082867,233.880005,111.540001
2018-12-26,154.059814,222.949997,1470.900024,11.00,130.839996,NaN,339.660675,134.179993,16.090000,42.520000,1047.849976,44.592968,253.669998,120.220001
2018-12-27,153.059998,225.139999,1461.640015,10.95,135.199997,80.000000,336.859924,134.520004,16.180000,43.009998,1052.900024,44.757092,255.570007,121.750000
2018-12-28,153.138428,223.130005,1478.020020,10.88,134.679993,NaN,343.142151,133.199997,16.090000,43.209999,1046.680054,45.133606,256.079987,121.239998
2018-12-31,154.618546,226.240005,1501.969971,11.06,136.970001,NaN,342.860168,131.089996,16.209999,43.720001,1044.959961,45.307384,267.660004,122.449997

In [ ]:
from datetime import datetime
from dateutil import relativedelta

d1 = datetime.strptime(start, "%Y-%m-%d")
d2 = datetime.strptime(end, "%Y-%m-%d")
delta = relativedelta.relativedelta(d2,d1)
print('How many years of investing?')
print('%s years' % delta.years)
number_of_years = delta.years

In [ ]:
days = (df.index[-1] - df.index[0]).days

In [ ]:
plt.figure(figsize=(12,8))
plt.plot(df)
plt.title('Cloud Services Stocks Closing Price')
plt.legend(labels=df.columns)

In [ ]:
plt.figure(figsize=(18,12))
plt.plot(normalize)
plt.title('Cloud Services Stocks Normalize')
plt.legend(labels=normalize.columns)

In [ ]:
stock_rets = df.pct_change().dropna()

In [ ]:
plt.figure(figsize=(12,8))
plt.plot(stock_rets)
plt.title('Cloud Services Stocks Returns')
plt.legend(labels=stock_rets.columns)

In [ ]:
plt.figure(figsize=(12,8))
plt.plot(stock_rets.cumsum())
plt.title('Cloud Services Stocks Returns Cumulative Sum')
plt.legend(labels=stock_rets.columns)

In [ ]:
sns.set(style='ticks')
ax = sns.pairplot(stock_rets, diag_kind='hist')

nplot = len(stock_rets.columns)
for i in range(nplot) :
    for j in range(nplot) :
        ax.axes[i, j].locator_params(axis='x', nbins=6, tight=True)

In [ ]:
ax = sns.PairGrid(stock_rets)
ax.map_upper(plt.scatter, color='purple')
ax.map_lower(sns.kdeplot, color='blue')
ax.map_diag(plt.hist, bins=30)
for i in range(nplot) :
    for j in range(nplot) :
        ax.axes[i, j].locator_params(axis='x', nbins=6, tight=True)

In [ ]:
plt.figure(figsize=(7,7))
corr = stock_rets.corr()

# plot the heatmap
sns.heatmap(corr, 
        xticklabels=corr.columns,
        yticklabels=corr.columns,
            cmap="Blues")

In [ ]:
# Box plot
stock_rets.plot(kind='box',figsize=(12,8))

In [ ]:
rets = stock_rets.dropna()

plt.figure(figsize=(12,8))
plt.scatter(rets.mean(), rets.std(),alpha = 0.5)

plt.title('Stocks Risk & Returns')
plt.xlabel('Expected returns')
plt.ylabel('Risk')
plt.grid(which='major')

for label, x, y in zip(rets.columns, rets.mean(), rets.std()):
    plt.annotate(
        label, 
        xy = (x, y), xytext = (50, 50),
        textcoords = 'offset points', ha = 'right', va = 'bottom',
        arrowprops = dict(arrowstyle = '-', connectionstyle = 'arc3,rad=-0.3'))